general:
  output_dir: /opt/ntl-systoolbox/outputs

servers:
  dc01:
    os: windows
    ip: 192.168.10.10
  dc02:
    os: windows
    ip: 192.168.10.11
  wms_db:
    os: linux
    ip: 192.168.10.21
    mysql:
      user: wmsuser
      password_env: WMS_DB_PASSWORD
      database: wms
  wms_app:
    os: linux
    ip: 192.168.10.22
